#include "particle.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

buffer ParticleBuffer {
	uint index;
	uint count;
	Particle particles[];
};

uniform float dt;

void main() {
	uint i = index + gl_GlobalInvocationID.x;
	if (i >= count) return;
	i = i % particles.length();
	
	Particle p = particles[i];
	
	vec3 position = particle_position(p);
	position += p.velocity * dt;

	set_particle_position(p, position);
	
	particles[i] = p;
}
